# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1004f601c1ebd88a144a59f2dcb83984e3f39343bea01ca26e7c7098885b91dcf8cf3042d1c534d643ec04ce305feb696e8c254fac4ebbe823c023d9426f614e

test:
  secret_key_base: 9e73ee1e15629979a914157d801420b721720e16c607798a584a592d6e69f1fbf9b62ddd8ad1effd15f462952fa83afaa50bc595d1fb0a71e760d05997454a14

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
